# Auto generated by Kolo at 2024-09-04 01:02:51.324507+00:00.
# Kolo version: 2.33.6
# Django version: 4.2.15
# Trace ID: trc_01J6X7Z34W2N3XC7BMEZ8ZN2J4

from agenda.models import Agenda
from agenda.models import Item
from agenda.models import SupportEngineer
from django.contrib.sessions.models import Session
from mocket import mocketize
from pytest_django.asserts import assertTemplateUsed
import datetime
import pytest
import time_machine


@mocketize(strict_mode=True)
@pytest.mark.django_db()
def test_my_view(client):
    with time_machine.travel('2024-09-04T00:46:46'):
        session, _created = Session.objects.get_or_create(
            session_data='.eJxVjU0KwjAQhe-StZS2SWaG7vQiYRwnNFhSMSko4t1tpQtdvr_vvUzgpY5hKXoP6WIG0zlz-DXPLFfNW8LTtNkNi8xLrs23s8elOa5Kc03CNc35tK_-UCOXceVIJOl6IN-CBReRABBJrUbvHAFSiz0DOGKrYtFHJs-d75UsKkTZoEVLWW-CPm7p_jRD-_4ApLdCyA:1slQfC:HKn0enFjDF4GaW0oE_wjAytT3MeHhMM7RTXq7f93YoE',
            expire_date=datetime.datetime(2024, 9, 17, 10, 21, 30, 906415, tzinfo=datetime.timezone.utc),
            defaults={
                'session_key': '4u9dvrsdqe1tdlpz3olryz7fcis58hno',
            },
        )
        support_engineer, _created = SupportEngineer.objects.get_or_create(
            password='pbkdf2_sha256$600000$wcnW3EuOwAprUMKt0F0SwV$lC3BfV4V2pqrmlQeKs4XXalLb8+/vFL2DxwGCKxH0T4=',
            last_login=datetime.datetime(2024, 9, 3, 10, 21, 30, 771488, tzinfo=datetime.timezone.utc),
            is_superuser=True,
            first_name='',
            last_name='',
            email='development.admin',
            is_staff=True,
            date_joined=datetime.datetime(2024, 9, 3, 9, 41, 32, 404460, tzinfo=datetime.timezone.utc),
            username='Terry@BrooksJr.com',
            defaults={
                'id': 14,
            },
        )
        support_engineer_2, _created = SupportEngineer.objects.get_or_create(
            password='pbkdf2_sha256$600000$wcnW3EuOwAprUMKt0F0SwV$lC3BfV4V2pqrmlQeKs4XXalLb8+/vFL2DxwGCKxH0T4=',
            first_name='Stephen',
            last_name='Savage',
            email='stephen.savage@learnosity.com',
            is_staff=True,
            date_joined=datetime.datetime(2024, 9, 2, 19, 51, 51, tzinfo=datetime.timezone.utc),
            username='ssavage',
            defaults={
                'id': 11,
            },
        )
        support_engineer_4, _created = SupportEngineer.objects.get_or_create(
            password='pbkdf2_sha256$600000$wcnW3EuOwAprUMKt0F0SwV$lC3BfV4V2pqrmlQeKs4XXalLb8+/vFL2DxwGCKxH0T4=',
            first_name='Terry',
            last_name='Brooks',
            email='terry.brooks@learnosity.com',
            is_staff=True,
            date_joined=datetime.datetime(2024, 9, 2, 19, 51, 51, tzinfo=datetime.timezone.utc),
            username='terry.brooks',
            defaults={
                'id': 13,
            },
        )
        support_engineer_3, _created = SupportEngineer.objects.get_or_create(
            password='pbkdf2_sha256$600000$wcnW3EuOwAprUMKt0F0SwV$lC3BfV4V2pqrmlQeKs4XXalLb8+/vFL2DxwGCKxH0T4=',
            last_login=datetime.datetime(2024, 9, 2, 19, 33, 23, 413185, tzinfo=datetime.timezone.utc),
            is_superuser=True,
            first_name='',
            last_name='',
            email='ssavage',
            is_staff=True,
            date_joined=datetime.datetime(2024, 9, 2, 19, 30, 6, 432544, tzinfo=datetime.timezone.utc),
            username='Stephen.Savage@learrnosity.com',
            defaults={
                'id': 10,
            },
        )
        support_engineer_5, _created = SupportEngineer.objects.get_or_create(
            password='pbkdf2_sha256$600000$wcnW3EuOwAprUMKt0F0SwV$lC3BfV4V2pqrmlQeKs4XXalLb8+/vFL2DxwGCKxH0T4=',
            first_name='Rich',
            last_name='Shupe',
            email='rich.shupe@learnosity.com',
            is_staff=True,
            date_joined=datetime.datetime(2024, 9, 2, 19, 51, 51, tzinfo=datetime.timezone.utc),
            username='rshupe',
            defaults={
                'id': 12,
            },
        )
        item_3, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='REVIEW',
            title='nulla dapibus dolor vel est donec odio',
            description='magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes',
            notes='Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
            defaults={
                'id': 235,
            },
        )
        item_7, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='CALLS',
            title='in tempor',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia',
            added_to_supportmail=True,
            defaults={
                'id': 237,
            },
        )
        item_13, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='FOCUS',
            title='vitae quam suspendisse potenti nullam porttitor',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam',
            notes='In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
            added_to_supportmail=True,
            defaults={
                'id': 199,
            },
        )
        item_15, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='FOCUS',
            title='eget orci vehicula condimentum curabitur',
            description='velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante',
            notes='Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
            added_to_supportmail=True,
            defaults={
                'id': 163,
            },
        )
        item_23, _created = Item.objects.get_or_create(
            creator=support_engineer,
            section='UPDATES',
            title='penatibus et',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi',
            notes='Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
            defaults={
                'id': 298,
            },
        )
        item_26, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='UPDATES',
            title='ultrices posuere cubilia',
            description='sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum',
            notes='Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
            added_to_supportmail=True,
            defaults={
                'id': 156,
            },
        )
        item_27, _created = Item.objects.get_or_create(
            creator=support_engineer,
            section='UPDATES',
            title='erat tortor sollicitudin mi sit amet lobortis',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius',
            added_to_supportmail=True,
            defaults={
                'id': 159,
            },
        )
        item_33, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='MISC',
            title='lobortis vel dapibus at diam nam',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo',
            notes='In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
            defaults={
                'id': 242,
            },
        )
        item_35, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='MISC',
            title='laoreet ut rhoncus',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse',
            notes='Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
            defaults={
                'id': 222,
            },
        )
        item_36, _created = Item.objects.get_or_create(
            creator=support_engineer,
            status='OPEN',
            section='MISC',
            title='orci luctus et',
            description='nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et',
            notes='Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
            defaults={
                'id': 207,
            },
        )
        item_38, _created = Item.objects.get_or_create(
            creator=support_engineer,
            section='MISC',
            title='sagittis sapien cum sociis natoque penatibus et',
            description='ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non',
            notes='Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
            added_to_supportmail=True,
            defaults={
                'id': 284,
            },
        )
        item_46, _created = Item.objects.get_or_create(
            creator=support_engineer,
            section='INTERNAL',
            title='interdum in ante vestibulum ante ipsum',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit',
            notes='Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
            defaults={
                'id': 257,
            },
        )
        item_10, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            status='OPEN',
            section='CALLS',
            title='posuere cubilia curae mauris viverra',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem',
            notes='In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
            added_to_supportmail=True,
            defaults={
                'id': 170,
            },
        )
        item_11, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            section='CALLS',
            title='amet cursus',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat',
            defaults={
                'id': 272,
            },
        )
        item_32, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            section='UPDATES',
            title='ut rhoncus',
            description='vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec',
            notes='Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
            added_to_supportmail=True,
            defaults={
                'id': 175,
            },
        )
        item_50, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            date_resolved=datetime.date(2023, 8, 7),
            section='INTERNAL',
            title='libero non mattis pulvinar nulla pede ullamcorper augue',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus',
            notes='Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
            added_to_supportmail=True,
            defaults={
                'id': 231,
            },
        )
        item_51, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            date_resolved=datetime.date(2023, 6, 9),
            status='OPEN',
            section='INTERNAL',
            title='enim blandit mi in porttitor pede justo eu',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum',
            notes='Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
            defaults={
                'id': 171,
            },
        )
        item_52, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            status='OPEN',
            section='INTERNAL',
            title='congue',
            description='porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus',
            added_to_supportmail=True,
            defaults={
                'id': 273,
            },
        )
        item_53, _created = Item.objects.get_or_create(
            creator=support_engineer_2,
            status='OPEN',
            section='INTERNAL',
            title='sapien placerat ante nulla justo aliquam quis',
            description='nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo',
            defaults={
                'id': 198,
            },
        )
        agenda, _created = Agenda.objects.get_or_create(
            driver=support_engineer_2,
            notetaker=support_engineer_4,
            defaults={
                'date': '2024-09-03',
            },
        )
        item_4, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            status='OPEN',
            section='REVIEW',
            title='ac enim in',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='dolor morbi vel lectus in quam fringilla rhoncus mauris enim',
            notes='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
            added_to_supportmail=True,
            defaults={
                'id': 267,
            },
        )
        item_8, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            status='OPEN',
            section='CALLS',
            title='parturient montes nascetur ridiculus mus etiam vel augue',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='venenatis turpis enim blandit mi in porttitor pede justo eu massa donec',
            notes='Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
            added_to_supportmail=True,
            defaults={
                'id': 204,
            },
        )
        item_9, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='CALLS',
            title='nascetur ridiculus mus vivamus',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed',
            notes='Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
            added_to_supportmail=True,
            defaults={
                'id': 282,
            },
        )
        item_19, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='NEEDS',
            title='quam a odio in hac',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='ut dolor morbi vel lectus in quam fringilla rhoncus mauris',
            notes='Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
            defaults={
                'id': 234,
            },
        )
        item_20, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='NEEDS',
            title='turpis integer aliquet massa id lobortis',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat',
            notes='Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
            added_to_supportmail=True,
            defaults={
                'id': 201,
            },
        )
        item_21, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            status='OPEN',
            section='NEEDS',
            title='integer non velit',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque',
            notes='In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
            defaults={
                'id': 295,
            },
        )
        item_30, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='UPDATES',
            title='suspendisse potenti',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin',
            notes='Fusce consequat. Nulla nisl. Nunc nisl.',
            added_to_supportmail=True,
            defaults={
                'id': 197,
            },
        )
        item_31, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            status='OPEN',
            section='UPDATES',
            title='nunc donec',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet',
            added_to_supportmail=True,
            defaults={
                'id': 215,
            },
        )
        item_39, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='MISC',
            title='dapibus',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='congue eget semper rutrum nulla nunc purus phasellus in felis',
            notes='Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
            defaults={
                'id': 268,
            },
        )
        item_40, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            status='OPEN',
            section='MISC',
            title='consequat morbi a ipsum integer a',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat',
            notes='Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
            added_to_supportmail=True,
            defaults={
                'id': 169,
            },
        )
        item_47, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            status='OPEN',
            section='INTERNAL',
            title='integer ac leo pellentesque ultrices mattis',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra',
            notes='Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
            added_to_supportmail=True,
            defaults={
                'id': 230,
            },
        )
        item_48, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='INTERNAL',
            title='convallis tortor risus dapibus augue vel accumsan',
            description='congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat',
            notes='Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
            added_to_supportmail=True,
            defaults={
                'id': 278,
            },
        )
        item_49, _created = Item.objects.get_or_create(
            creator=support_engineer_4,
            section='INTERNAL',
            title='rhoncus sed vestibulum sit amet',
            description='morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo',
            notes='In congue. Etiam justo. Etiam pretium iaculis justo.',
            defaults={
                'id': 241,
            },
        )
        item, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            section='REVIEW',
            title='rhoncus aliquam lacus',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien',
            notes='Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
            defaults={
                'id': 195,
            },
        )
        item_2, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            status='OPEN',
            section='REVIEW',
            title='augue vestibulum ante ipsum',
            description='sit amet lobortis sapien sapien non mi integer ac neque duis bibendum',
            notes='Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
            added_to_supportmail=True,
            defaults={
                'id': 287,
            },
        )
        item_14, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            status='OPEN',
            section='FOCUS',
            title='at dolor quis',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida',
            notes='Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
            defaults={
                'id': 203,
            },
        )
        item_22, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            section='UPDATES',
            title='eu',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem',
            notes='Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
            added_to_supportmail=True,
            defaults={
                'id': 250,
            },
        )
        item_24, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            section='UPDATES',
            title='nulla pede ullamcorper augue a suscipit',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='turpis sed ante vivamus tortor duis mattis egestas metus aenean',
            defaults={
                'id': 285,
            },
        )
        item_25, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            date_resolved=datetime.date(2023, 7, 9),
            section='UPDATES',
            title='gravida sem praesent id massa',
            description='suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce',
            notes='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
            defaults={
                'id': 280,
            },
        )
        item_28, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            status='OPEN',
            section='UPDATES',
            title='vel augue vestibulum rutrum rutrum',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue',
            notes='Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
            added_to_supportmail=True,
            defaults={
                'id': 262,
            },
        )
        item_29, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            section='UPDATES',
            title='vulputate justo in blandit ultrices',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor',
            notes='Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
            added_to_supportmail=True,
            defaults={
                'id': 289,
            },
        )
        item_34, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            section='MISC',
            title='convallis eget eleifend luctus ultricies eu nibh',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis',
            notes='Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
            added_to_supportmail=True,
            defaults={
                'id': 210,
            },
        )
        item_37, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            section='MISC',
            title='ut dolor morbi vel lectus in',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit',
            defaults={
                'id': 200,
            },
        )
        item_42, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            status='OPEN',
            section='INTERNAL',
            title='libero rutrum ac',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum',
            notes='Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
            defaults={
                'id': 152,
            },
        )
        item_43, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            date_resolved=datetime.date(2023, 10, 10),
            status='OPEN',
            section='INTERNAL',
            title='urna pretium',
            description='velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros',
            notes='Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
            added_to_supportmail=True,
            defaults={
                'id': 292,
            },
        )
        item_44, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            status='OPEN',
            section='INTERNAL',
            title='nisi volutpat',
            description='sit amet cursus id turpis integer aliquet massa id lobortis',
            notes='Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
            defaults={
                'id': 184,
            },
        )
        item_45, _created = Item.objects.get_or_create(
            creator=support_engineer_3,
            status='OPEN',
            section='INTERNAL',
            title='sagittis sapien cum',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus',
            notes='Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
            added_to_supportmail=True,
            defaults={
                'id': 291,
            },
        )
        item_5, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            section='REVIEW',
            title='volutpat sapien arcu sed augue aliquam erat',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam',
            notes='Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
            defaults={
                'id': 202,
            },
        )
        item_6, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            status='OPEN',
            section='REVIEW',
            title='justo',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet',
            notes='Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
            added_to_supportmail=True,
            defaults={
                'id': 185,
            },
        )
        item_12, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            status='OPEN',
            section='CALLS',
            title='velit',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit',
            added_to_supportmail=True,
            defaults={
                'id': 214,
            },
        )
        item_16, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            status='OPEN',
            section='FOCUS',
            title='pretium quis',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus',
            notes='Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
            defaults={
                'id': 153,
            },
        )
        item_17, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            status='OPEN',
            section='FOCUS',
            title='faucibus orci luctus et ultrices',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi',
            notes='Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
            added_to_supportmail=True,
            defaults={
                'id': 275,
            },
        )
        item_18, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            status='OPEN',
            section='FOCUS',
            title='vel ipsum praesent blandit lacinia erat vestibulum sed',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor',
            notes='Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
            added_to_supportmail=True,
            defaults={
                'id': 276,
            },
        )
        item_41, _created = Item.objects.get_or_create(
            creator=support_engineer_5,
            status='OPEN',
            section='MISC',
            title='nulla neque libero convallis eget',
            link_to_ticket='https://www.zendesk.com/fake_ticket',
            description='phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque',
            added_to_supportmail=True,
            defaults={
                'id': 224,
            },
        )
        agenda_2, _created = Agenda.objects.get_or_create(
            driver=support_engineer_5,
            notetaker=support_engineer_4,
            defaults={
                'date': '1970-01-01',
            },
        )

        response = client.get(
            '/',
            HTTP_COOKIE='nhhc-csrf=bOtAK48te4P25zTvBdlJ72IHm9ZepuS3; ph_phc_zQM74CuK5pp8UqgLvLlUF1yU38gp4XUAw9JLfp03fK3_posthog=%7B%22distinct_id%22%3A%22Terry%40BrooksJr.com%22%2C%22%24sesid%22%3A%5B1724220995560%2C%2201917393-3c09-7f1a-a731-776238d1420c%22%2C1724220914697%5D%2C%22%24epp%22%3Atrue%7D; messages=.eJyVzDEKwzAMAMCvGM3ChEL30LFruoVghKsmTm0JpGTw79utc9cbbp4hpd1VUmN3WhlwwMsVYTpz_srrrLUHL6vwMxQJ5IHk2FR6bFTGymSiXo4es7YICLDg_-WDzfp4M9W33-1XLR9ftDbv:1slQfC:ha8yB8Vaxu-zdw_od57NlM9dpH3h-QzaxaPwb7OFmyk; csrftoken=SaSMemWdj7gpC34NaNuoVnzkB7Oapt4P; sessionid=4u9dvrsdqe1tdlpz3olryz7fcis58hno',
            content_type='text/plain',
        )

        assert response.status_code == 200
        assertTemplateUsed(response, 'index.html')
        assertTemplateUsed(response, 'layouts/base-layout.html')
        assertTemplateUsed(response, 'layouts/_styles.html')
        assertTemplateUsed(response, 'includes/_pre-loader.html')
        assertTemplateUsed(response, 'includes/sidebar.html')
        assertTemplateUsed(response, 'includes/modals.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/layout/column.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/layout/column.html')
        assertTemplateUsed(response, 'bootstrap5/layout/row.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'martor/bootstrap/editor.html')
        assertTemplateUsed(response, 'martor/bootstrap/toolbar.html')
        assertTemplateUsed(response, 'martor/bootstrap/guide.html')
        assertTemplateUsed(response, 'martor/bootstrap/emoji.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'martor/bootstrap/editor.html')
        assertTemplateUsed(response, 'martor/bootstrap/toolbar.html')
        assertTemplateUsed(response, 'martor/bootstrap/guide.html')
        assertTemplateUsed(response, 'martor/bootstrap/emoji.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/layout/column.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/layout/column.html')
        assertTemplateUsed(response, 'bootstrap5/layout/row.html')
        assertTemplateUsed(response, 'bootstrap5/layout/baseinput.html')
        assertTemplateUsed(response, 'bootstrap5/layout/baseinput.html')
        assertTemplateUsed(response, 'bootstrap5/whole_uni_form.html')
        assertTemplateUsed(response, 'bootstrap5/display_form.html')
        assertTemplateUsed(response, 'bootstrap5/errors.html')
        assertTemplateUsed(response, 'bootstrap5/inputs.html')
        assertTemplateUsed(response, 'bootstrap5/uni_form.html')
        assertTemplateUsed(response, 'bootstrap5/errors.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'martor/bootstrap/editor.html')
        assertTemplateUsed(response, 'martor/bootstrap/toolbar.html')
        assertTemplateUsed(response, 'martor/bootstrap/guide.html')
        assertTemplateUsed(response, 'martor/bootstrap/emoji.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'martor/bootstrap/editor.html')
        assertTemplateUsed(response, 'martor/bootstrap/toolbar.html')
        assertTemplateUsed(response, 'martor/bootstrap/guide.html')
        assertTemplateUsed(response, 'martor/bootstrap/emoji.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'bootstrap5/field.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text_and_errors.html')
        assertTemplateUsed(response, 'bootstrap5/layout/field_errors_block.html')
        assertTemplateUsed(response, 'bootstrap5/layout/help_text.html')
        assertTemplateUsed(response, 'includes/navbar.html')
        assertTemplateUsed(response, 'includes/stats.html')
        assertTemplateUsed(response, 'includes/review_list.html')
        assertTemplateUsed(response, 'includes/monitor_list.html')
        assertTemplateUsed(response, 'includes/focus_list2.html')
        assertTemplateUsed(response, 'includes/calls_list2.html')
        assertTemplateUsed(response, 'includes/internal_list2.html')
        assertTemplateUsed(response, 'includes/needs_list2.html')
        assertTemplateUsed(response, 'includes/updates_list2.html')
        assertTemplateUsed(response, 'includes/item-log.html')
        assertTemplateUsed(response, 'layouts/base-layout.html')
        assertTemplateUsed(response, 'layouts/_styles.html')
        assertTemplateUsed(response, 'layouts/_scripts.html')
        assertTemplateUsed(response, 'layouts/_scripts.html')
        assertTemplateUsed(response, 'debug_toolbar/base.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/theme_selector.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_button.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')
        assertTemplateUsed(response, 'debug_toolbar/includes/panel_content.html')

