# Generated by Django 4.2.5 on 2023-10-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="date",
            field=models.CharField(
                default="2023-10-03", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
