# Generated by Django 4.2.5 on 2023-09-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="link_to_ticket",
            field=models.URLField(default=""),
        ),
    ]
