# Generated by Django 4.2.5 on 2023-09-07 23:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_item_link_to_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="call_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="focus_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="internal_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="misc_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="monitoring_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="needs_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="review_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="update_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(null=True), blank=True, size=None
            ),
        ),
    ]
