# Generated by Django 4.2.15 on 2024-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_date_alter_item_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.CharField(default='2024-08-30', primary_key=True, serialize=False, unique=True),
        ),
    ]
