# Generated by Django 4.2.15 on 2024-09-04 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.CharField(default='2024-09-03', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supportmail',
            name='edition',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=3),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_of_event', models.DateField()),
                ('description', models.CharField(max_length=65535)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
                'db_table': 'personal_updates',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ClientCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_of_event', models.DateField()),
                ('topic', models.CharField(max_length=65535)),
                ('client', models.CharField(max_length=65535)),
                ('leading_call', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Call',
                'verbose_name_plural': 'Client Calls',
                'db_table': 'client_calls',
                'ordering': ['-date_of_event'],
            },
        ),
    ]
