# Generated by Django 4.2.5 on 2023-09-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_alter_agenda_call_items_alter_agenda_focus_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="date",
            field=models.CharField(
                default="2023-09-07", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
