# Generated by Django 4.2.6 on 2023-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0004_alter_agenda_options_alter_agenda_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agenda",
            options={
                "get_latest_by": ["date"],
                "ordering": ["-date"],
                "verbose_name": "Agenda",
                "verbose_name_plural": "Agendas",
            },
        ),
        migrations.AlterField(
            model_name="agenda",
            name="date",
            field=models.CharField(
                default="2023-10-09", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
