# Generated by Django 4.2.5 on 2023-09-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0005_alter_agenda_call_items_alter_agenda_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="date_resolved",
            field=models.DateField(blank=True, null=True),
        ),
    ]
