# Generated by Django 4.2.6 on 2023-10-11 22:24

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0005_alter_agenda_options_alter_agenda_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportmail",
            name="issues",
        ),
        migrations.AddField(
            model_name="item",
            name="added_to_supportmail_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="date",
            field=models.CharField(
                default="2023-10-11", primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="notes",
            field=martor.models.MartorField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("OPEN", "Open"),
                    ("FYI", "Visibility Only"),
                    ("RESOLVED", "Resolved"),
                    ("PUBLISHED", "Published"),
                    ("ACCEPTED", "Feature Accepted"),
                    ("REJECTED", "Feature Rejected"),
                    ("BACKLOG", "Feature Pending"),
                ],
                default="NEW",
                max_length=65535,
            ),
        ),
        migrations.AlterField(
            model_name="supportmail",
            name="edition",
            field=models.CharField(
                choices=[
                    ("1", "Janurary"),
                    ("2", "February"),
                    ("3", "March"),
                    ("4", "April"),
                    ("5", "May"),
                    ("6", "June"),
                    ("7", "July"),
                    ("8", "August"),
                    ("9", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "Decemeber"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="win_oops",
            name="description",
            field=martor.models.MartorField(),
        ),
    ]
