# Generated by Django 4.2.5 on 2023-09-09 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0009_alter_item_section_alter_item_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenda",
            name="call_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="focus_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="internal_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="misc_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="monitoring_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="needs_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="review_items",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="update_items",
        ),
    ]
