# Generated by Django 4.2.5 on 2023-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0010_remove_agenda_call_items_remove_agenda_focus_items_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Agenda Item",
                "verbose_name_plural": "Agenda Item",
            },
        ),
        migrations.AlterField(
            model_name="agenda",
            name="date",
            field=models.CharField(
                default="2023-09-10", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
